name: orct2srv CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockr.it
        uses: docker/login-action@v2
        with:
          registry: dockr.it
          username: ${{ secrets.DOCKR_USER }}
          password: ${{ secrets.DOCKR_PASS }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: | 
            dockr.it/orct2srv:latest
            dockr.it/orct2srv:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max